# -*- coding: utf-8 -*-
import sys
import typing
from typing import TYPE_CHECKING, Any, Dict

if TYPE_CHECKING:
    import ast

from .._fast import *

def location_of(*args, **kwargs) -> "Any": ...
def kw(arg: str, value: "ast.expr") -> "ast.keyword": ...
def kwargs(**kwargs: "ast.expr") -> "typing.List[ast.keyword]": ...
def parse(*args, **kwargs) -> "ast.Module": ...
def And(*args, **kwargs) -> "ast.And": ...
def Attribute(*args, **kwargs) -> "ast.Attribute": ...
def BinOp(*args, **kwargs) -> "ast.BinOp": ...
def BoolOp(*args, **kwargs) -> "ast.BoolOp": ...
def Call(*args, **kwargs) -> "ast.Call": ...
def Compare(*args, **kwargs) -> "ast.Compare": ...
def If(*args, **kwargs) -> "ast.If": ...
def IfExp(*args, **kwargs) -> "ast.IfExp": ...
def Lambda(*args, **kwargs) -> "ast.Lambda": ...
def Name(*args, **kwargs) -> "ast.Name": ...
def NameConstant(*args, **kwargs) -> "ast.NameConstant": ...
def Not(*args, **kwargs) -> "ast.Not": ...
def Pass(*args, **kwargs) -> "ast.Pass": ...
def Subscript(*args, **kwargs) -> "ast.Subscript": ...
def List(*args, **kwargs) -> "ast.List": ...
def Try(*args, **kwargs) -> "ast.Try": ...
def Tuple(*args, **kwargs) -> "ast.Tuple": ...
def UnaryOp(*args, **kwargs) -> "ast.UnaryOp": ...
def arg(*args, **kwargs) -> "ast.arg": ...
def keyword(*args, **kwargs) -> "ast.keyword": ...

if sys.version_info < (3, 9):
    def Index(*args, **kwargs) -> "ast.Index": ...

if sys.version_info < (3, 8):
    def Num(*args, **kwargs) -> "ast.Num": ...
    def Str(*args, **kwargs) -> "ast.Str": ...

else:
    def Num(*args, **kwargs) -> "ast.Constant": ...
    def Str(*args, **kwargs) -> "ast.Constant": ...
    def Constant(*args, **kwargs) -> "ast.Constant": ...
