name: pyccolo

on: [push, pull_request]

jobs:
  build:

    if: ${{ matrix.os == 'macos' && matrix.python-minor-version < 10 }}:
    runs-on: 'macos-13'
    if: ${{ matrix.os == 'macos' && matrix.python-minor-version >= 10 }}:
    runs-on: 'macos-latest'
    if: ${{ matrix.os != 'macos' }}:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ 'macos', 'ubuntu-latest', 'windows-latest' ]
        python-minor-version: [ 7, 8, 9, 10, 11, 12 ]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.${{ matrix.python-minor-version }}'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
    - name: Lint with ruff
      run: make lint
    - name: Run unit tests with pytest (skip typechecking, coverage)
      if: matrix.os == 'windows-latest'
      run: pytest
    - name: Run typechecking with mypy and unit tests with pytest (skip coverage)
      if: matrix.os == 'macos'
      run: |
        make typecheck
        pytest
    - name: Run typechecking with mypy and unit tests with pytest (including coverage)
      if: matrix.os == 'ubuntu-latest'
      run: make check_ci
    - name: Upload coverage report
      if: matrix.os == 'ubuntu-latest'
      uses: codecov/codecov-action@v1
      with:
        token: '${{ secrets.CODECOV_TOKEN }}'
        files: ./coverage.xml
        env_vars: PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true
